directories:
  output: dist
  buildResources: build
appId: com.chronos.history.diff.app
productName: ChronosHistoryDiff
asar: true
asarUnpack:
  - '**/node_modules/glob/**/*'
files:
  - filter:
      - main.js
      - preload.js
      - public/**/*
      - out/**/*
      - package.json
mac:
  category: public.app-category.developer-tools
  icon: public/logo.png
  target: dmg
win:
  target:
    - nsis
    - portable
  icon: public/logo.png
nsis:
  oneClick: false
  allowToChangeInstallationDirectory: true
  shortcutName: ChronosHistoryDiff
  artifactName: ${productName}-Setup-${version}.${ext}
linux:
  target:
    - AppImage
    - deb
  icon: public/logo.png
  category: Development
  maintainer: Ilidio Martins <ilidio.martins@gmail.com>
electronVersion: 39.2.7
